In [1]:
import os
import cv2 
from google.colab.patches import cv2_imshow
import csv
import random
import time
import numpy as np
import pandas as pd
import matplotlib.image as mping
import matplotlib.pyplot as plt
import seaborn as sns
from keras import optimizers
from matplotlib.font_manager import FontProperties
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei']
from keras.utils.np_utils import to_categorical
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from keras.optimizers import RMSprop
from keras.models import Sequential
from keras import utils as np_utils
from keras import backend as K
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow as tf

In [ ]:
csvfile = open('/content/drive/MyDrive/Colab/Mango/train.csv')
reader = csv.reader(csvfile)

In [ ]:
labels = []
for line in csvfile:
  tmp = [line[0],line[1]]
  labels.append(tmp)

picnum = len(labels)
print(picnum)

6131


In [ ]:
x = []
y = []

for i in range(len(labels)):
  print(labels)
  labels[i][i] = labels[i][i].replace('A')
  labels[i][i] = labels[i][i].replace('B')
  labels[i][i] = labels[i][i].replace('C')

[['i', 'm'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0', '0'], ['0

TypeError: ignored

In [ ]:
import os
import zipfile


# zipfile example
def zip_list(file_path):
    zf = zipfile.ZipFile(file_path)
    zf.extractall()


if __name__ == '__main__':
    file_path = '/content/drive/MyDrive/Colab/Mango.zip'
    zip_list(file_path)

In [2]:
traincsv = pd.read_csv('/content/train.csv')
print(traincsv.shape)
#print(traincsv.columns)
#print(traincsv.shape[0])

(6130, 2)


In [3]:
testcsv = pd.read_csv('/content/Test.csv')
print(testcsv.shape)
#testcsv.head()
#print(testcsv.columns)
#print(traincsv.shape[0])

(250, 2)


In [ ]:
'''
for i in range(traincsv.shape[0]):
  print(str(i)+ str('.jpg') )
'''

"\nfor i in range(traincsv.shape[0]):\n  print(str(i)+ str('.jpg') )\n"

In [ ]:
'''
get_filename = '/content/Mango/Train_Image'
path = os.listdir(get_filename)
print(path)
'''
'''
for i in range path:
  print(i)
'''

'''
get_filename = '/content/Mango/Train_Image/'
path = os.listdir(get_filename)

print(path)
'''

'''
def read_filename(path):

  for imagefiles in path:
    img = cv2.imread(get_filename+ '/' +imagefiles)
    #cv2_imshow(img)
    
    
  return  
'''

"\ndef read_filename(path):\n\n  for imagefiles in path:\n    img = cv2.imread(get_filename+ '/' +imagefiles)\n    #cv2_imshow(img)\n    \n    \n  return  \n"

In [ ]:
!nvidia-smi

Fri Apr 30 13:23:15 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    58W / 149W |   2311MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import keras  

from keras.models import Sequential  

from keras.layers import Dense, Dropout, Flatten  

from keras.layers import Conv2D, MaxPooling2D  

from keras.utils import to_categorical  

from keras.preprocessing import image  

import numpy as np  

import pandas as pd  

import matplotlib.pyplot as plt  

from sklearn.model_selection import train_test_split  

from tqdm import tqdm  

%matplotlib inline  

In [6]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm

In [7]:
import cv2 
from google.colab.patches import cv2_imshow
import os
import numpy as np
import pandas as pd
from PIL import Image

get_filename = '/content/Mango/Train_Image'
path = os.listdir(get_filename)

train_image = []  


for i in path:  

  img = image.load_img(get_filename + '/' + str(i),target_size=(100,100,3),grayscale=False)  

  img = np.array(img)/255 
 
  #img_array = np.array(img) 

  train_image.append(img)  
  
X = np.array(train_image) 
Xr = X.reshape(6130,100*100*3)
print(Xr.shape)

(6130, 30000)


In [8]:
get_testfilename = '/content/Mango/Test_Image'
testpath = os.listdir(get_testfilename)

test_image = []  


for j in testpath:  
  

  testimg = image.load_img(get_testfilename + '/' + str(j),target_size=(100,100,3),grayscale=False)  

  testimg = np.array(testimg)/255 
 
  #img_array = np.array(img) 

  test_image.append(testimg)  
  
x = np.array(test_image) 
xr = x.reshape(250,100*100*3)
print(xr.shape)


(250, 30000)


In [ ]:
'''
plt.imshow(X[2])
traincsv['label'][2]
'''
plt.show(x[3])
testcsv['label'][3]


ValueError: ignored

In [9]:
Y = traincsv['label'].values

Y = to_categorical(Y)
print(Y.shape)

(6130, 3)


In [10]:
y = testcsv['label'].values

y = to_categorical(y)
print(y.shape)

(250, 3)


In [11]:
X_train, x_test, Y_train, y_test = (X,x,Y,y)


model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(100,100,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
#model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])
model.summary()






model.save("chinese_mod")


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 98, 98, 32)        896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 96, 96, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 48, 48, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 48, 48, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 147456)            0         
_________________________________________________________________
dense (Dense)                (None, 128)               18874496  
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 3

In [28]:
model.fit(X_train, Y_train, epochs=10)

Epoch 1/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1729 - accuracy: 0.9506
Epoch 2/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0196 - accuracy: 0.9966
Epoch 3/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0129 - accuracy: 0.9976
Epoch 4/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0079 - accuracy: 0.9995
Epoch 5/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0081 - accuracy: 0.9987
Epoch 6/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0076 - accuracy: 0.9989
Epoch 7/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0100 - accuracy: 0.9974
Epoch 8/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0081 - accuracy: 0.9980
Epoch 9/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0054 - accuracy: 0.9985
Epoch 10/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0132 - accura

In [31]:
model.fit(x_test, y_test, epochs=10)

Epoch 1/10
8/8 [==============================] - 0s 33ms/step - loss: 0.4548 - accuracy: 0.8440
Epoch 2/10
8/8 [==============================] - 0s 25ms/step - loss: 0.0820 - accuracy: 0.9760
Epoch 3/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0356 - accuracy: 0.9920
Epoch 4/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0320 - accuracy: 0.9880
Epoch 5/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0162 - accuracy: 0.9920
Epoch 6/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0173 - accuracy: 0.9880
Epoch 7/10
8/8 [==============================] - 0s 23ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 8/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0092 - accuracy: 0.9960
Epoch 9/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 10/10
8/8 [==============================] - 0s 24ms/step - loss: 0.0015 - accuracy: 1.0000


In [29]:
loss, accuracy = model.evaluate(X_train, Y_train)
print("訓練資料集的準確度 = {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(x_test, y_test)
print("測試資料集的準確度 = {:.4f}".format(accuracy))

192/192 [==============================] - 2s 8ms/step - loss: 0.0051 - accuracy: 0.9989
訓練資料集的準確度 = 0.9989
8/8 [==============================] - 0s 7ms/step - loss: 0.3887 - accuracy: 0.8720
測試資料集的準確度 = 0.8720


In [14]:
print(X_train.shape)
print(Y_train.shape)
print(x_test.shape)
print(y_test.shape)
print('____________________')
X_trainr = X_train.reshape(6130,30000)
Y_trainr = Y_train.reshape(6130,3)
x_testr = x_test.reshape(250,30000)
y_testr = y_test.reshape(250,3)

(6130, 100, 100, 3)
(6130, 3)
(250, 100, 100, 3)
(250, 3)
____________________


In [34]:
import numpy as np
import pandas as pd
import math
import scipy.stats as sci
from sklearn.model_selection import train_test_split
from sklearn import ensemble, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

forest = ensemble.RandomForestClassifier(n_estimators=10)
forest_fit = forest.fit(x_testr, y_testr)
test_y_predicted = forest.predict(x_testr)
accuracy = metrics.accuracy_score(y_testr, test_y_predicted)
C = confusion_matrix(y_testr.argmax(axis=1), test_y_predicted.argmax(axis=1))
print("Score",forest.score(x_testr, y_testr))
print(accuracy)
print(C)
print(classification_report(y_testr, test_y_predicted))

Score 0.932
0.932
[[84  0  0]
 [ 4 92  0]
 [ 6  0 64]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        84
           1       1.00      0.96      0.98        96
           2       1.00      0.91      0.96        70

   micro avg       1.00      0.93      0.96       250
   macro avg       1.00      0.93      0.96       250
weighted avg       1.00      0.93      0.96       250
 samples avg       0.93      0.93      0.93       250



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
