In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from keras.models import Sequential, load_model
from keras.datasets import cifar10
from keras.utils import np_utils,plot_model
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D

In [2]:
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
x_train = X_train.astype('float32')/255
x_test = X_test.astype('float32')/255
y_train = np_utils.to_categorical(Y_train)
y_test = np_utils.to_categorical(Y_test)

(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
x_train = X_train.astype('float32')/255
x_test = X_test.astype('float32')/255
y_train = np_utils.to_categorical(Y_train)
y_test = np_utils.to_categorical(Y_test)


170500096/170498071 [==============================] - 4s 0us/step


In [3]:
model = Sequential()
model.add(Conv2D(filters=64, kernel_size=3, input_shape=(32, 32, 3), activation='relu', padding='same'))
model.add(Conv2D(filters=64, kernel_size=3, input_shape=(32, 32, 3), activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(rate=0.25))
model.add(Dense(10, activation='softmax'))

In [4]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 64)        1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 64)        36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 16, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 128)       73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 16, 128)       147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 8, 128)         0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 8, 8, 128)         1

In [5]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10, batch_size=64, verbose=1)

Epoch 1/10
782/782 [==============================] - 38s 9ms/step - loss: 1.8037 - accuracy: 0.3214
Epoch 2/10
782/782 [==============================] - 7s 9ms/step - loss: 1.0231 - accuracy: 0.6364
Epoch 3/10
782/782 [==============================] - 7s 9ms/step - loss: 0.7688 - accuracy: 0.7298
Epoch 4/10
782/782 [==============================] - 7s 9ms/step - loss: 0.6238 - accuracy: 0.7776
Epoch 5/10
782/782 [==============================] - 7s 9ms/step - loss: 0.4989 - accuracy: 0.8238
Epoch 6/10
782/782 [==============================] - 7s 9ms/step - loss: 0.4055 - accuracy: 0.8566
Epoch 7/10
782/782 [==============================] - 7s 9ms/step - loss: 0.3194 - accuracy: 0.8876
Epoch 8/10
782/782 [==============================] - 7s 9ms/step - loss: 0.2680 - accuracy: 0.9071
Epoch 9/10
782/782 [==============================] - 7s 9ms/step - loss: 0.2238 - accuracy: 0.9210
Epoch 10/10
782/782 [==============================] - 7s 9ms/step - loss: 0.1941 - accuracy: 0.930

In [ ]:
pirnt(x_train[1])
print(y_train[1])

NameError: ignored

In [6]:
loss, accuracy = model.evaluate(x_test, y_test)
print('Test:')
print('Loss:', loss)
print('Accuracy:', accuracy)

313/313 [==============================] - 2s 4ms/step - loss: 0.9638 - accuracy: 0.7687
Test:
Loss: 0.9637547135353088
Accuracy: 0.7687000036239624


In [7]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.3610 - accuracy: 0.8736
Epoch 2/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2769 - accuracy: 0.9048
Epoch 3/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2501 - accuracy: 0.9139
Epoch 4/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2385 - accuracy: 0.9180
Epoch 5/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2231 - accuracy: 0.9247
Epoch 6/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2137 - accuracy: 0.9273
Epoch 7/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2070 - accuracy: 0.9310
Epoch 8/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.2015 - accuracy: 0.9327
Epoch 9/10
1563/1563 [==============================] - 10s 7ms/step - loss: 0.1898 - accuracy: 0.9360
Epoch 10/10
1563/1563 [==============================] - 10s 7ms/step - l

In [8]:
model.fit(x_test, y_test, epochs=10)

Epoch 1/10
313/313 [==============================] - 2s 7ms/step - loss: 0.8419 - accuracy: 0.7358
Epoch 2/10
313/313 [==============================] - 2s 7ms/step - loss: 0.5109 - accuracy: 0.8252
Epoch 3/10
313/313 [==============================] - 2s 7ms/step - loss: 0.3011 - accuracy: 0.8944
Epoch 4/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1877 - accuracy: 0.9345
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1339 - accuracy: 0.9531
Epoch 6/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1243 - accuracy: 0.9568
Epoch 7/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1195 - accuracy: 0.9605
Epoch 8/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1507 - accuracy: 0.9512
Epoch 9/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1054 - accuracy: 0.9654
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1208 - accuracy: 0.9609

In [10]:
loss, accuracy = model.evaluate(x_train, y_train)
print("訓練資料集的準確度 = {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(x_test, y_test)
print("測試資料集的準確度 = {:.4f}".format(accuracy))

1563/1563 [==============================] - 6s 4ms/step - loss: 0.4890 - accuracy: 0.8666
訓練資料集的準確度 = 0.8666
313/313 [==============================] - 1s 4ms/step - loss: 0.0743 - accuracy: 0.9747
測試資料集的準確度 = 0.9747


In [11]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print('____________________')
x_trainr = x_train.reshape(50000,3072)
y_trainr = y_train.reshape(50000,10)
x_testr = x_test.reshape(10000,3072)
y_testr = y_test.reshape(10000,10)

(50000, 32, 32, 3)
(50000, 10)
(10000, 32, 32, 3)
(10000, 10)
____________________


In [13]:
import numpy as np
import pandas as pd
import math
import scipy.stats as sci
from sklearn.model_selection import train_test_split
from sklearn import ensemble, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

forest = ensemble.RandomForestClassifier(n_estimators=10)
forest_fit = forest.fit(x_testr, y_testr)
test_y_predicted = forest.predict(x_testr)
accuracy = metrics.accuracy_score(y_testr, test_y_predicted)
C = confusion_matrix(y_testr.argmax(axis=1), test_y_predicted.argmax(axis=1))
print("Score",forest.score(x_testr, y_testr))
print(accuracy)
print(C)
print(classification_report(y_testr, test_y_predicted))

Score 0.8553
0.8553
[[1000    0    0    0    0    0    0    0    0    0]
 [ 145  855    0    0    0    0    0    0    0    0]
 [ 152    0  848    0    0    0    0    0    0    0]
 [ 192    0    0  808    0    0    0    0    0    0]
 [ 138    0    0    0  862    0    0    0    0    0]
 [ 153    0    0    0    0  847    0    0    0    0]
 [ 135    0    0    0    0    0  865    0    0    0]
 [ 155    0    0    0    0    0    0  845    0    0]
 [ 127    0    0    0    0    0    0    0  873    0]
 [ 131    0    0    0    0    0    0    0    0  869]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94      1000
           1       1.00      0.85      0.92      1000
           2       1.00      0.85      0.92      1000
           3       1.00      0.81      0.89      1000
           4       1.00      0.86      0.93      1000
           5       1.00      0.85      0.92      1000
           6       1.00      0.86      0.93      1000
           7    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
