安裝所需的環境與套件

In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from keras.models import Sequential, load_model
from keras.datasets import cifar10
from keras.utils import np_utils,plot_model
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D

載入cifar10資料集，並且分為訓練集(圖像與CSV)與測試集(圖像與CSV)

In [ ]:
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
x_train = X_train.astype('float32')/255
x_test = X_test.astype('float32')/255
y_train = np_utils.to_categorical(Y_train)
y_test = np_utils.to_categorical(Y_test)

(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
x_train = X_train.astype('float32')/255
x_test = X_test.astype('float32')/255
y_train = np_utils.to_categorical(Y_train)
y_test = np_utils.to_categorical(Y_test)


建構訓練的CNN模型

In [ ]:
'''
model = Sequential()
model.add(Conv2D(filters=64, kernel_size=3, input_shape=(32, 32, 3), activation='relu', padding='same'))
model.add(Conv2D(filters=64, kernel_size=3, input_shape=(32, 32, 3), activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(rate=0.25))
model.add(Dense(10, activation='softmax'))
'''

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(32,32,3)))
#model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))


model.add(Conv2D(64, kernel_size=(3, 3),activation='relu',input_shape=(32,32,3)))
#model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))


model.add(Conv2D(128, kernel_size=(3, 3),activation='relu',input_shape=(32,32,3)))
#model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
'''
model.add(Conv2D(256, kernel_size=(3, 3),activation='relu',input_shape=(32,32,3)))
#model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
'''


#model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
#model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])
model.summary()


Model: "sequential_27"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_71 (Conv2D)           (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d_56 (MaxPooling (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_72 (Conv2D)           (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_57 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_73 (Conv2D)           (None, 4, 4, 128)         73856     
_________________________________________________________________
max_pooling2d_58 (MaxPooling (None, 2, 2, 128)         0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 512)             

顯示模型的結構

In [ ]:
print(model.summary())

Model: "sequential_27"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_71 (Conv2D)           (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d_56 (MaxPooling (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_72 (Conv2D)           (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_57 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_73 (Conv2D)           (None, 4, 4, 128)         73856     
_________________________________________________________________
max_pooling2d_58 (MaxPooling (None, 2, 2, 128)         0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 512)             

顯示訓練集的訓練過程

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10, batch_size=64, verbose=1)

Epoch 1/10
782/782 [==============================] - 8s 9ms/step - loss: 1.7869 - accuracy: 0.3390
Epoch 2/10
782/782 [==============================] - 7s 9ms/step - loss: 1.2484 - accuracy: 0.5552
Epoch 3/10
782/782 [==============================] - 7s 9ms/step - loss: 1.0607 - accuracy: 0.6291
Epoch 4/10
782/782 [==============================] - 7s 9ms/step - loss: 0.9425 - accuracy: 0.6703
Epoch 5/10
782/782 [==============================] - 7s 9ms/step - loss: 0.8443 - accuracy: 0.7039
Epoch 6/10
782/782 [==============================] - 7s 9ms/step - loss: 0.7677 - accuracy: 0.7323
Epoch 7/10
782/782 [==============================] - 7s 9ms/step - loss: 0.7008 - accuracy: 0.7590
Epoch 8/10
782/782 [==============================] - 7s 9ms/step - loss: 0.6549 - accuracy: 0.7719
Epoch 9/10
782/782 [==============================] - 7s 9ms/step - loss: 0.6010 - accuracy: 0.7897
Epoch 10/10
782/782 [==============================] - 7s 9ms/step - loss: 0.5518 - accuracy: 0.8061

In [ ]:
'''
pirnt(x_train[1])
print(y_train[1])
'''

NameError: ignored

In [ ]:
'''
loss, accuracy = model.evaluate(x_test, y_test)
print('Test:')
print('Loss:', loss)
print('Accuracy:', accuracy)
'''

"\nloss, accuracy = model.evaluate(x_test, y_test)\nprint('Test:')\nprint('Loss:', loss)\nprint('Accuracy:', accuracy)\n"

顯示訓練集訓練的過程

In [ ]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.6213 - accuracy: 0.7817
Epoch 2/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.5509 - accuracy: 0.8061
Epoch 3/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.5048 - accuracy: 0.8216
Epoch 4/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.4617 - accuracy: 0.8367
Epoch 5/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.4247 - accuracy: 0.8485
Epoch 6/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.3908 - accuracy: 0.8600
Epoch 7/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.3604 - accuracy: 0.8721
Epoch 8/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.3337 - accuracy: 0.8808
Epoch 9/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.3115 - accuracy: 0.8884
Epoch 10/10
1563/1563 [==============================] - 12s 8ms/step - l

In [ ]:
'''
model.fit(x_test, y_test, epochs=10)
'''

Epoch 1/10
313/313 [==============================] - 6s 19ms/step - loss: 0.8237 - accuracy: 0.7284
Epoch 2/10
313/313 [==============================] - 6s 18ms/step - loss: 0.5389 - accuracy: 0.8136
Epoch 3/10
313/313 [==============================] - 6s 18ms/step - loss: 0.3585 - accuracy: 0.8741
Epoch 4/10
313/313 [==============================] - 6s 18ms/step - loss: 0.2207 - accuracy: 0.9231
Epoch 5/10
313/313 [==============================] - 6s 18ms/step - loss: 0.1784 - accuracy: 0.9393
Epoch 6/10
313/313 [==============================] - 6s 18ms/step - loss: 0.1723 - accuracy: 0.9396
Epoch 7/10
313/313 [==============================] - 6s 18ms/step - loss: 0.1257 - accuracy: 0.9569
Epoch 8/10
313/313 [==============================] - 6s 18ms/step - loss: 0.1285 - accuracy: 0.9585
Epoch 9/10
313/313 [==============================] - 6s 18ms/step - loss: 0.1192 - accuracy: 0.9602
Epoch 10/10
313/313 [==============================] - 6s 18ms/step - loss: 0.1027 - accura

顯示訓練及測試集的loss和accuracy

In [ ]:
loss, accuracy = model.evaluate(x_train, y_train)
print("訓練資料集的準確度 = {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(x_test, y_test)
print("測試資料集的準確度 = {:.4f}".format(accuracy))

1563/1563 [==============================] - 6s 4ms/step - loss: 0.2927 - accuracy: 0.8996
訓練資料集的準確度 = 0.8996
313/313 [==============================] - 1s 4ms/step - loss: 1.4985 - accuracy: 0.6222
測試資料集的準確度 = 0.6222


改變資料型態(dimension)
4D─2D

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print('____________________')
x_trainr = x_train.reshape(50000,3072)
y_trainr = y_train.reshape(50000,10)
x_testr = x_test.reshape(10000,3072)
y_testr = y_test.reshape(10000,10)

(50000, 32, 32, 3)
(50000, 10)
(10000, 32, 32, 3)
(10000, 10)
____________________


繪製混淆矩陣

In [ ]:
import numpy as np
import pandas as pd
import math
import scipy.stats as sci
from sklearn.model_selection import train_test_split
from sklearn import ensemble, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

forest = ensemble.RandomForestClassifier(n_estimators=10)
forest_fit = forest.fit(x_testr, y_testr)
test_y_predicted = forest.predict(x_testr)
accuracy = metrics.accuracy_score(y_testr, test_y_predicted)
C = confusion_matrix(y_testr.argmax(axis=1), test_y_predicted.argmax(axis=1))
print("Score",forest.score(x_testr, y_testr))
print(accuracy)
print(C)
print(classification_report(y_testr, test_y_predicted))

Score 0.8545
0.8545
[[1000    0    0    0    0    0    0    0    0    0]
 [ 131  869    0    0    0    0    0    0    0    0]
 [ 158    0  842    0    0    0    0    0    0    0]
 [ 175    0    0  825    0    0    0    0    0    0]
 [ 137    0    0    0  863    0    0    0    0    0]
 [ 167    0    0    1    0  832    0    0    0    0]
 [ 139    0    0    0    1    0  860    0    0    0]
 [ 174    0    0    0    0    0    0  826    0    0]
 [ 105    0    0    0    0    0    0    0  895    0]
 [ 154    0    0    0    0    0    0    0    1  845]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94      1000
           1       1.00      0.87      0.93      1000
           2       1.00      0.84      0.91      1000
           3       1.00      0.82      0.90      1000
           4       1.00      0.86      0.93      1000
           5       1.00      0.83      0.91      1000
           6       1.00      0.86      0.92      1000
           7    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
